server:
  port: 8082
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ldjc?serverTimezone=GMT%2b8
    username: root
    password: 210210
  redis:
    host: 192.168.119.134
    port: 6379
    password: 210210
    #springboot配置文件上传的大小
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB


#mybatis日志输出
#mybatis:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#mybatis-plus日志输出
mybatis-plus:
  global-config:
    db-config:
      #防止在mybatis-plus进行增加操作,表中数据id值特别大(自增)
      #配置数据库表中主键的自增策略
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#使用xml方式告诉mubatis-plus需要使用的表名前缀
#  global-config:
#    db-config:
#      table-prefix: sys

#文件上传:
files:
  upload:
    path: D:/项目/files/

